apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wearefrank-skeleton-test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

