site_name: wearefrank-skeleton-test
site_description: wearefrank-skeleton-test " documentation"

nav:
  - Introduction: index.md
  - FrankDoc: frankdoc.md

theme: readthedocs

plugins:
  - techdocs-core
