apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-world
  description: Hello World example for WSDL
spec:
  type: wsdl
  lifecycle: deprecated
  owner: foo
  definition:
    $text: https://gist.githubusercontent.com/SorenPoulsen/ad7db25d2616f96a91849d77d01bb328/raw/db6b5735b8b0a87ccb506f564591758a7d3c21f1/test.wsdl
